INSERT INTO actividades (
    nombre_actividad,
    tipo_actividad,
    fecha_inicio,
    fecha_fin,
    dias_semana,
    hora_inicio,
    hora_fin,
    duracion,
    requisitos,
    costo,
    cupo_maximo,
    cupo_disponible,
    descripcion,
    id_evento,
    estado
  )
VALUES -- =====================================================
  -- EVENTO 1
  -- Jornada de Planificación de Oratoria y Liturgia
  -- =====================================================
  (
    'Registro y presentación de participantes',
    'Integración',
    '2026-01-12',
    '2026-01-12',
    'Lunes',
    '09:00:00',
    '09:30:00',
    '30 minutos',
    'Ser miembro o invitado del área de Oratoria y Liturgia.',
    0.00,
    40,
    40,
    'Registro de participantes y presentación general de los objetivos de la jornada.',
    1,
    'Activo'
  ),
  (
    'Presentación del plan anual de actividades',
    'Planificación',
    '2026-01-12',
    '2026-01-12',
    'Lunes',
    '09:30:00',
    '10:30:00',
    '1 hora',
    'Participación en el área de Oratoria y Liturgia.',
    0.00,
    40,
    40,
    'Presentación de la propuesta de actividades académicas, formativas y pastorales para la gestión.',
    1,
    'Activo'
  ),
  (
    'Mesa de trabajo y organización de equipos',
    'Trabajo grupal',
    '2026-01-12',
    '2026-01-12',
    'Lunes',
    '10:45:00',
    '12:00:00',
    '1 hora y 15 minutos',
    'Participar previamente en la jornada.',
    0.00,
    40,
    40,
    'Organización de equipos de trabajo y asignación preliminar de responsabilidades.',
    1,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 2
  -- Taller de Formación en Expresión Oral
  -- =====================================================
  (
    'Introducción a la expresión oral',
    'Taller',
    '2026-01-19',
    '2026-01-19',
    'Lunes',
    '15:00:00',
    '15:40:00',
    '40 minutos',
    'Interés en desarrollar habilidades de comunicación.',
    0.00,
    35,
    35,
    'Introducción a los fundamentos de la comunicación y expresión oral.',
    2,
    'Activo'
  ),
  (
    'Técnicas de manejo de la voz',
    'Taller práctico',
    '2026-01-19',
    '2026-01-19',
    'Lunes',
    '15:50:00',
    '16:40:00',
    '50 minutos',
    'Participar en la actividad introductoria.',
    0.00,
    35,
    35,
    'Ejercicios prácticos para mejorar la dicción, proyección y manejo de la voz.',
    2,
    'Activo'
  ),
  (
    'Práctica de exposición ante el público',
    'Práctica',
    '2026-01-19',
    '2026-01-19',
    'Lunes',
    '16:50:00',
    '18:00:00',
    '1 hora y 10 minutos',
    'Participación en las actividades previas.',
    0.00,
    35,
    35,
    'Práctica individual de presentaciones y exposiciones breves ante los participantes.',
    2,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 3
  -- Encuentro de Preparación Litúrgica
  -- =====================================================
  (
    'Reflexión sobre la participación litúrgica',
    'Reflexión',
    '2026-01-24',
    '2026-01-24',
    'Sábado',
    '10:00:00',
    '10:40:00',
    '40 minutos',
    'Interés en participar en actividades litúrgicas.',
    0.00,
    50,
    50,
    'Espacio de reflexión sobre la importancia de la participación consciente y activa en la liturgia.',
    3,
    'Activo'
  ),
  (
    'Organización de ministerios y servicios',
    'Formación',
    '2026-01-24',
    '2026-01-24',
    'Sábado',
    '10:50:00',
    '11:40:00',
    '50 minutos',
    'Participar en el encuentro.',
    0.00,
    50,
    50,
    'Organización y coordinación de los diferentes servicios necesarios para las celebraciones.',
    3,
    'Activo'
  ),
  (
    'Ensayo general de celebración litúrgica',
    'Ensayo',
    '2026-01-24',
    '2026-01-24',
    'Sábado',
    '11:40:00',
    '12:30:00',
    '50 minutos',
    'Participación en las actividades de preparación.',
    0.00,
    50,
    50,
    'Ensayo y coordinación general de las funciones de los participantes.',
    3,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 4
  -- Jornada de Oratoria y Comunicación Universitaria
  -- =====================================================
  (
    'Charla sobre comunicación universitaria',
    'Conferencia',
    '2026-01-29',
    '2026-01-29',
    'Jueves',
    '14:30:00',
    '15:15:00',
    '45 minutos',
    'Participación abierta a la comunidad universitaria.',
    0.00,
    80,
    80,
    'Charla introductoria sobre la importancia de la comunicación en la formación universitaria.',
    4,
    'Activo'
  ),
  (
    'Taller de construcción de discursos',
    'Taller',
    '2026-01-29',
    '2026-01-29',
    'Jueves',
    '15:30:00',
    '16:30:00',
    '1 hora',
    'Interés en mejorar las habilidades de oratoria.',
    0.00,
    50,
    50,
    'Desarrollo de técnicas para estructurar y organizar un discurso.',
    4,
    'Activo'
  ),
  (
    'Práctica de argumentación y debate',
    'Práctica',
    '2026-01-29',
    '2026-01-29',
    'Jueves',
    '16:45:00',
    '18:00:00',
    '1 hora y 15 minutos',
    'Participación en el taller de construcción de discursos.',
    0.00,
    50,
    50,
    'Ejercicio práctico de argumentación, intercambio de ideas y debate respetuoso.',
    4,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 5
  -- Encuentro de Bienvenida y Formación Comunitaria
  -- =====================================================
  (
    'Registro y bienvenida institucional',
    'Integración',
    '2026-02-03',
    '2026-02-03',
    'Martes',
    '10:00:00',
    '10:30:00',
    '30 minutos',
    'Ser miembro de la comunidad universitaria.',
    0.00,
    100,
    100,
    'Recepción y bienvenida de los participantes al encuentro.',
    5,
    'Activo'
  ),
  (
    'Dinámica de integración universitaria',
    'Integración',
    '2026-02-03',
    '2026-02-03',
    'Martes',
    '10:30:00',
    '11:30:00',
    '1 hora',
    'Participación en el encuentro.',
    0.00,
    100,
    100,
    'Actividad grupal orientada a fortalecer la integración y convivencia.',
    5,
    'Activo'
  ),
  (
    'Presentación de valores y participación comunitaria',
    'Formación',
    '2026-02-03',
    '2026-02-03',
    'Martes',
    '11:40:00',
    '12:30:00',
    '50 minutos',
    'Participación abierta.',
    0.00,
    100,
    100,
    'Presentación y reflexión sobre valores, participación y compromiso comunitario.',
    5,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 6
  -- Taller de Oratoria para la Comunidad Universitaria
  -- =====================================================
  (
    'Técnicas básicas de oratoria',
    'Taller',
    '2026-02-10',
    '2026-02-10',
    'Martes',
    '15:00:00',
    '15:45:00',
    '45 minutos',
    'Interés en mejorar la expresión oral.',
    0.00,
    40,
    40,
    'Introducción a las principales técnicas y herramientas de la oratoria.',
    6,
    'Activo'
  ),
  (
    'Manejo del lenguaje corporal',
    'Taller práctico',
    '2026-02-10',
    '2026-02-10',
    'Martes',
    '15:55:00',
    '16:40:00',
    '45 minutos',
    'Participación en el taller.',
    0.00,
    40,
    40,
    'Ejercicios para mejorar la postura, gestos y comunicación no verbal.',
    6,
    'Activo'
  ),
  (
    'Presentaciones orales individuales',
    'Práctica',
    '2026-02-10',
    '2026-02-10',
    'Martes',
    '16:50:00',
    '18:00:00',
    '1 hora y 10 minutos',
    'Participación en las actividades anteriores.',
    0.00,
    40,
    40,
    'Presentaciones breves de los participantes aplicando las técnicas desarrolladas.',
    6,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 7
  -- Jornada de Formación Litúrgica Universitaria
  -- =====================================================
  (
    'Introducción a la celebración litúrgica',
    'Formación',
    '2026-02-14',
    '2026-02-14',
    'Sábado',
    '09:30:00',
    '10:15:00',
    '45 minutos',
    'Interés en participar en actividades litúrgicas.',
    0.00,
    60,
    60,
    'Introducción a los principales elementos y momentos de la celebración litúrgica.',
    7,
    'Activo'
  ),
  (
    'Formación sobre participación y servicio',
    'Taller',
    '2026-02-14',
    '2026-02-14',
    'Sábado',
    '10:30:00',
    '11:20:00',
    '50 minutos',
    'Participación en la jornada.',
    0.00,
    60,
    60,
    'Formación sobre las responsabilidades y actitudes necesarias para el servicio litúrgico.',
    7,
    'Activo'
  ),
  (
    'Práctica de preparación litúrgica',
    'Práctica',
    '2026-02-14',
    '2026-02-14',
    'Sábado',
    '11:30:00',
    '12:30:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    60,
    60,
    'Ejercicio práctico de organización y preparación de una celebración.',
    7,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 8
  -- Encuentro de Lectores y Animadores Litúrgicos
  -- =====================================================
  (
    'Técnicas de proclamación de lecturas',
    'Taller',
    '2026-02-18',
    '2026-02-18',
    'Miércoles',
    '16:00:00',
    '16:45:00',
    '45 minutos',
    'Interés en participar como lector litúrgico.',
    0.00,
    40,
    40,
    'Formación práctica sobre lectura, dicción y proclamación adecuada.',
    8,
    'Activo'
  ),
  (
    'Formación para animadores litúrgicos',
    'Formación',
    '2026-02-18',
    '2026-02-18',
    'Miércoles',
    '16:55:00',
    '17:40:00',
    '45 minutos',
    'Participar en el encuentro.',
    0.00,
    40,
    40,
    'Orientación para la animación y acompañamiento de las celebraciones.',
    8,
    'Activo'
  ),
  (
    'Ensayo de lectores y animadores',
    'Ensayo',
    '2026-02-18',
    '2026-02-18',
    'Miércoles',
    '17:45:00',
    '18:45:00',
    '1 hora',
    'Participar en las actividades de formación.',
    0.00,
    40,
    40,
    'Práctica conjunta para aplicar las orientaciones desarrolladas durante el encuentro.',
    8,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 9
  -- Conferencia sobre Comunicación, Fe y Liderazgo
  -- =====================================================
  (
    'Apertura y presentación de la conferencia',
    'Conferencia',
    '2026-02-23',
    '2026-02-23',
    'Lunes',
    '18:00:00',
    '18:20:00',
    '20 minutos',
    'Participación abierta.',
    0.00,
    120,
    120,
    'Presentación de los objetivos y contenidos principales de la conferencia.',
    9,
    'Activo'
  ),
  (
    'Ponencia sobre comunicación y liderazgo',
    'Conferencia',
    '2026-02-23',
    '2026-02-23',
    'Lunes',
    '18:20:00',
    '19:20:00',
    '1 hora',
    'Participación abierta.',
    0.00,
    120,
    120,
    'Exposición sobre la relación entre comunicación, liderazgo y formación humana.',
    9,
    'Activo'
  ),
  (
    'Espacio de diálogo y preguntas',
    'Conversatorio',
    '2026-02-23',
    '2026-02-23',
    'Lunes',
    '19:30:00',
    '20:15:00',
    '45 minutos',
    'Participación en la conferencia.',
    0.00,
    120,
    120,
    'Espacio destinado al intercambio de preguntas, ideas y reflexiones.',
    9,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 10
  -- Jornada de Integración de Oratoria y Liturgia
  -- =====================================================
  (
    'Apertura e integración de participantes',
    'Integración',
    '2026-02-27',
    '2026-02-27',
    'Viernes',
    '09:00:00',
    '09:40:00',
    '40 minutos',
    'Participación abierta a la comunidad universitaria.',
    0.00,
    80,
    80,
    'Actividad inicial de bienvenida e integración entre los participantes.',
    10,
    'Activo'
  ),
  (
    'Taller de comunicación al servicio de la comunidad',
    'Taller',
    '2026-02-27',
    '2026-02-27',
    'Viernes',
    '09:50:00',
    '10:50:00',
    '1 hora',
    'Participación en la jornada.',
    0.00,
    60,
    60,
    'Actividad formativa sobre la utilización de las habilidades comunicativas en el servicio y participación comunitaria.',
    10,
    'Activo'
  ),
  (
    'Actividad práctica de expresión y participación',
    'Práctica',
    '2026-02-27',
    '2026-02-27',
    'Viernes',
    '11:00:00',
    '12:00:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    60,
    60,
    'Actividad práctica que integra expresión oral, trabajo grupal y participación comunitaria.',
    10,
    'Activo'
  ),
  (
    'Cierre y reflexión final',
    'Reflexión',
    '2026-02-27',
    '2026-02-27',
    'Viernes',
    '12:00:00',
    '12:30:00',
    '30 minutos',
    'Participación en la jornada.',
    0.00,
    80,
    80,
    'Espacio final de reflexión, evaluación y cierre de la jornada.',
    10,
    'Activo'
  );
INSERT INTO actividades (
    nombre_actividad,
    tipo_actividad,
    fecha_inicio,
    fecha_fin,
    dias_semana,
    hora_inicio,
    hora_fin,
    duracion,
    requisitos,
    costo,
    cupo_maximo,
    cupo_disponible,
    descripcion,
    id_evento,
    estado
  )
VALUES -- =====================================================
  -- EVENTO 11
  -- Jornada de Bienvenida y Formación en Oratoria
  -- =====================================================
  (
    'Registro y bienvenida de participantes',
    'Integración',
    '2026-03-04',
    '2026-03-04',
    'Miércoles',
    '09:00:00',
    '09:30:00',
    '30 minutos',
    'Pertenecer a la comunidad universitaria.',
    0.00,
    100,
    100,
    'Registro de participantes y bienvenida a la jornada de formación.',
    11,
    'Activo'
  ),
  (
    'Dinámica de expresión y presentación',
    'Dinámica',
    '2026-03-04',
    '2026-03-04',
    'Miércoles',
    '09:30:00',
    '10:30:00',
    '1 hora',
    'Participación en la jornada.',
    0.00,
    100,
    100,
    'Dinámicas destinadas a fortalecer la seguridad y confianza al momento de hablar frente a otras personas.',
    11,
    'Activo'
  ),
  (
    'Introducción a las técnicas de oratoria',
    'Taller',
    '2026-03-04',
    '2026-03-04',
    'Miércoles',
    '10:45:00',
    '11:45:00',
    '1 hora',
    'Participación en la jornada.',
    0.00,
    100,
    100,
    'Presentación de técnicas básicas para mejorar la expresión oral y la comunicación ante el público.',
    11,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 12
  -- Taller de Expresión Oral y Comunicación Efectiva
  -- =====================================================
  (
    'Ejercicios de dicción y vocalización',
    'Taller práctico',
    '2026-03-10',
    '2026-03-10',
    'Martes',
    '15:00:00',
    '15:45:00',
    '45 minutos',
    'Interés en mejorar la expresión oral.',
    0.00,
    40,
    40,
    'Ejercicios prácticos para mejorar la pronunciación, dicción y claridad al hablar.',
    12,
    'Activo'
  ),
  (
    'Manejo de la voz y respiración',
    'Taller práctico',
    '2026-03-10',
    '2026-03-10',
    'Martes',
    '15:55:00',
    '16:45:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    40,
    40,
    'Técnicas de respiración, volumen, ritmo y proyección de la voz.',
    12,
    'Activo'
  ),
  (
    'Lenguaje corporal y comunicación no verbal',
    'Taller',
    '2026-03-10',
    '2026-03-10',
    'Martes',
    '17:00:00',
    '18:00:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    40,
    40,
    'Ejercicios para trabajar postura, gestos, contacto visual y expresión corporal.',
    12,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 13
  -- Encuentro de Formación para Lectores Litúrgicos
  -- =====================================================
  (
    'Formación sobre proclamación de la Palabra',
    'Formación',
    '2026-03-14',
    '2026-03-14',
    'Sábado',
    '10:00:00',
    '10:45:00',
    '45 minutos',
    'Interés en participar como lector litúrgico.',
    0.00,
    50,
    50,
    'Orientación sobre la importancia de la proclamación de la Palabra y el servicio del lector.',
    13,
    'Activo'
  ),
  (
    'Técnicas de lectura y dicción litúrgica',
    'Taller',
    '2026-03-14',
    '2026-03-14',
    'Sábado',
    '10:55:00',
    '11:45:00',
    '50 minutos',
    'Participación en la formación.',
    0.00,
    50,
    50,
    'Ejercicios de lectura, pronunciación, pausas y manejo adecuado de la voz.',
    13,
    'Activo'
  ),
  (
    'Práctica de proclamación',
    'Práctica',
    '2026-03-14',
    '2026-03-14',
    'Sábado',
    '11:45:00',
    '12:30:00',
    '45 minutos',
    'Participación en las actividades previas.',
    0.00,
    50,
    50,
    'Práctica individual y grupal de proclamación de lecturas litúrgicas.',
    13,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 14
  -- Jornada de Liderazgo, Comunicación y Servicio
  -- =====================================================
  (
    'Introducción al liderazgo universitario',
    'Conferencia',
    '2026-03-19',
    '2026-03-19',
    'Jueves',
    '14:30:00',
    '15:15:00',
    '45 minutos',
    'Participación abierta a estudiantes.',
    0.00,
    80,
    80,
    'Reflexión sobre liderazgo, responsabilidad y participación dentro de la comunidad universitaria.',
    14,
    'Activo'
  ),
  (
    'Comunicación para el trabajo en equipo',
    'Taller',
    '2026-03-19',
    '2026-03-19',
    'Jueves',
    '15:25:00',
    '16:20:00',
    '55 minutos',
    'Participación en la jornada.',
    0.00,
    80,
    80,
    'Actividad orientada a mejorar la comunicación y coordinación entre integrantes de un equipo.',
    14,
    'Activo'
  ),
  (
    'Dinámica de liderazgo y servicio',
    'Dinámica',
    '2026-03-19',
    '2026-03-19',
    'Jueves',
    '16:30:00',
    '17:30:00',
    '1 hora',
    'Participación en la jornada.',
    0.00,
    80,
    80,
    'Dinámicas grupales para fortalecer el liderazgo colaborativo y la actitud de servicio.',
    14,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 15
  -- Encuentro de Preparación Litúrgica Universitaria
  -- =====================================================
  (
    'Organización de la celebración litúrgica',
    'Planificación',
    '2026-03-25',
    '2026-03-25',
    'Miércoles',
    '16:00:00',
    '16:45:00',
    '45 minutos',
    'Participación en el equipo litúrgico.',
    0.00,
    50,
    50,
    'Planificación de los diferentes elementos y servicios necesarios para la celebración.',
    15,
    'Activo'
  ),
  (
    'Distribución de servicios litúrgicos',
    'Coordinación',
    '2026-03-25',
    '2026-03-25',
    'Miércoles',
    '16:55:00',
    '17:40:00',
    '45 minutos',
    'Participación en el encuentro.',
    0.00,
    50,
    50,
    'Asignación y coordinación de lectores, animadores y demás servicios litúrgicos.',
    15,
    'Activo'
  ),
  (
    'Ensayo de la celebración',
    'Ensayo',
    '2026-03-25',
    '2026-03-25',
    'Miércoles',
    '17:45:00',
    '18:45:00',
    '1 hora',
    'Participación en las actividades de preparación.',
    0.00,
    50,
    50,
    'Ensayo general de las intervenciones y momentos de la celebración litúrgica.',
    15,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 16
  -- Festival Universitario de Oratoria
  -- =====================================================
  (
    'Registro y presentación de participantes',
    'Organización',
    '2026-03-30',
    '2026-03-30',
    'Lunes',
    '14:00:00',
    '14:30:00',
    '30 minutos',
    'Inscripción previa al festival.',
    0.00,
    100,
    100,
    'Registro de participantes y presentación de las reglas del festival.',
    16,
    'Activo'
  ),
  (
    'Presentación de discursos',
    'Oratoria',
    '2026-03-30',
    '2026-03-30',
    'Lunes',
    '14:30:00',
    '16:00:00',
    '1 hora y 30 minutos',
    'Inscripción previa.',
    0.00,
    100,
    100,
    'Presentación de discursos preparados por los participantes.',
    16,
    'Activo'
  ),
  (
    'Evaluación y deliberación',
    'Evaluación',
    '2026-03-30',
    '2026-03-30',
    'Lunes',
    '16:15:00',
    '17:00:00',
    '45 minutos',
    'Ser participante o miembro del jurado.',
    0.00,
    100,
    100,
    'Evaluación de las presentaciones considerando expresión, argumentación y desenvolvimiento.',
    16,
    'Activo'
  ),
  (
    'Reconocimiento y cierre',
    'Clausura',
    '2026-03-30',
    '2026-03-30',
    'Lunes',
    '17:00:00',
    '17:30:00',
    '30 minutos',
    'Participación en el festival.',
    0.00,
    100,
    100,
    'Reconocimiento a los participantes y cierre del festival universitario.',
    16,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 17
  -- Jornada de Preparación para Semana Santa
  -- =====================================================
  (
    'Reflexión y preparación espiritual',
    'Reflexión',
    '2026-04-01',
    '2026-04-01',
    'Miércoles',
    '10:00:00',
    '10:45:00',
    '45 minutos',
    'Participación abierta a la comunidad universitaria.',
    0.00,
    100,
    100,
    'Espacio de reflexión y preparación de la comunidad universitaria para Semana Santa.',
    17,
    'Activo'
  ),
  (
    'Organización de celebraciones de Semana Santa',
    'Planificación',
    '2026-04-01',
    '2026-04-01',
    'Miércoles',
    '10:55:00',
    '11:45:00',
    '50 minutos',
    'Participación en el equipo de organización.',
    0.00,
    60,
    60,
    'Coordinación de las celebraciones, servicios y participación de la comunidad universitaria.',
    17,
    'Activo'
  ),
  (
    'Ensayo de cantos y participación litúrgica',
    'Ensayo',
    '2026-04-01',
    '2026-04-01',
    'Miércoles',
    '11:50:00',
    '12:40:00',
    '50 minutos',
    'Participación en la jornada.',
    0.00,
    60,
    60,
    'Preparación práctica de cantos y participación de los diferentes equipos litúrgicos.',
    17,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 18
  -- Encuentro Universitario de Reflexión y Comunicación
  -- =====================================================
  (
    'Dinámica de escucha activa',
    'Dinámica',
    '2026-04-08',
    '2026-04-08',
    'Miércoles',
    '15:30:00',
    '16:15:00',
    '45 minutos',
    'Participación abierta.',
    0.00,
    60,
    60,
    'Actividad destinada a fortalecer la escucha, atención y comprensión durante la comunicación.',
    18,
    'Activo'
  ),
  (
    'Taller de comunicación interpersonal',
    'Taller',
    '2026-04-08',
    '2026-04-08',
    'Miércoles',
    '16:25:00',
    '17:20:00',
    '55 minutos',
    'Participación en el encuentro.',
    0.00,
    60,
    60,
    'Taller sobre comunicación interpersonal, empatía y expresión de ideas.',
    18,
    'Activo'
  ),
  (
    'Conversatorio de reflexión universitaria',
    'Conversatorio',
    '2026-04-08',
    '2026-04-08',
    'Miércoles',
    '17:30:00',
    '18:30:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    60,
    60,
    'Espacio abierto para compartir experiencias, opiniones y reflexiones sobre la comunicación.',
    18,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 19
  -- Taller de Oratoria: Argumentación y Discurso
  -- =====================================================
  (
    'Estructura y preparación del discurso',
    'Taller',
    '2026-04-14',
    '2026-04-14',
    'Martes',
    '14:00:00',
    '14:50:00',
    '50 minutos',
    'Interés en desarrollar habilidades de oratoria.',
    0.00,
    45,
    45,
    'Aprendizaje de técnicas para organizar introducción, desarrollo y conclusión de un discurso.',
    19,
    'Activo'
  ),
  (
    'Técnicas de argumentación',
    'Taller práctico',
    '2026-04-14',
    '2026-04-14',
    'Martes',
    '15:00:00',
    '15:50:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    45,
    45,
    'Ejercicios para construir argumentos claros, coherentes y convincentes.',
    19,
    'Activo'
  ),
  (
    'Presentación y evaluación de discursos',
    'Práctica',
    '2026-04-14',
    '2026-04-14',
    'Martes',
    '16:00:00',
    '17:00:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    45,
    45,
    'Presentación de discursos breves y evaluación de las técnicas desarrolladas.',
    19,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 20
  -- Jornada de Formación para Animadores Litúrgicos
  -- =====================================================
  (
    'Rol del animador litúrgico',
    'Formación',
    '2026-04-18',
    '2026-04-18',
    'Sábado',
    '09:30:00',
    '10:15:00',
    '45 minutos',
    'Interés en participar en la animación litúrgica.',
    0.00,
    50,
    50,
    'Formación sobre las funciones y responsabilidades del animador dentro de la celebración.',
    20,
    'Activo'
  ),
  (
    'Técnicas de animación y participación',
    'Taller',
    '2026-04-18',
    '2026-04-18',
    'Sábado',
    '10:25:00',
    '11:15:00',
    '50 minutos',
    'Participación en la jornada.',
    0.00,
    50,
    50,
    'Técnicas para promover la participación activa y ordenada de la comunidad.',
    20,
    'Activo'
  ),
  (
    'Práctica de animación litúrgica',
    'Práctica',
    '2026-04-18',
    '2026-04-18',
    'Sábado',
    '11:25:00',
    '12:30:00',
    '1 hora y 5 minutos',
    'Participación en las actividades formativas.',
    0.00,
    50,
    50,
    'Simulación y práctica de diferentes momentos de animación durante una celebración.',
    20,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 21
  -- Encuentro de Comunicación y Valores Universitarios
  -- =====================================================
  (
    'Comunicación responsable y convivencia',
    'Conferencia',
    '2026-04-23',
    '2026-04-23',
    'Jueves',
    '15:00:00',
    '15:45:00',
    '45 minutos',
    'Participación abierta.',
    0.00,
    80,
    80,
    'Reflexión sobre la importancia de una comunicación responsable dentro de la comunidad universitaria.',
    21,
    'Activo'
  ),
  (
    'Taller de empatía y comunicación',
    'Taller',
    '2026-04-23',
    '2026-04-23',
    'Jueves',
    '15:55:00',
    '16:50:00',
    '55 minutos',
    'Participación en el encuentro.',
    0.00,
    80,
    80,
    'Actividad práctica para desarrollar empatía, respeto y comunicación asertiva.',
    21,
    'Activo'
  ),
  (
    'Conversatorio sobre valores universitarios',
    'Conversatorio',
    '2026-04-23',
    '2026-04-23',
    'Jueves',
    '17:00:00',
    '18:00:00',
    '1 hora',
    'Participación en el encuentro.',
    0.00,
    80,
    80,
    'Espacio de diálogo sobre valores, convivencia y responsabilidad dentro de la universidad.',
    21,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 22
  -- Jornada Universitaria de Oratoria y Participación
  -- =====================================================
  (
    'Apertura y dinámica de integración',
    'Integración',
    '2026-04-29',
    '2026-04-29',
    'Miércoles',
    '09:00:00',
    '09:40:00',
    '40 minutos',
    'Participación abierta a estudiantes.',
    0.00,
    100,
    100,
    'Actividad de apertura destinada a integrar a los participantes y promover su participación.',
    22,
    'Activo'
  ),
  (
    'Presentaciones de expresión oral',
    'Oratoria',
    '2026-04-29',
    '2026-04-29',
    'Miércoles',
    '09:50:00',
    '10:50:00',
    '1 hora',
    'Participación en la jornada.',
    0.00,
    100,
    100,
    'Presentación de exposiciones breves sobre temas de interés académico y social.',
    22,
    'Activo'
  ),
  (
    'Dinámica de participación estudiantil',
    'Dinámica',
    '2026-04-29',
    '2026-04-29',
    'Miércoles',
    '11:00:00',
    '11:45:00',
    '45 minutos',
    'Participación en las actividades anteriores.',
    0.00,
    100,
    100,
    'Actividad grupal para fomentar el diálogo, participación y trabajo colaborativo.',
    22,
    'Activo'
  ),
  (
    'Cierre y reflexión de la jornada',
    'Reflexión',
    '2026-04-29',
    '2026-04-29',
    'Miércoles',
    '11:45:00',
    '12:15:00',
    '30 minutos',
    'Participación en la jornada.',
    0.00,
    100,
    100,
    'Espacio final de reflexión y evaluación de las actividades desarrolladas.',
    22,
    'Activo'
  );
INSERT INTO actividades (
    nombre_actividad,
    tipo_actividad,
    fecha_inicio,
    fecha_fin,
    dias_semana,
    hora_inicio,
    hora_fin,
    duracion,
    requisitos,
    costo,
    cupo_maximo,
    cupo_disponible,
    descripcion,
    id_evento,
    estado
  )
VALUES -- =====================================================
  -- EVENTO 23
  -- Jornada Universitaria de Comunicación y Oratoria
  -- =====================================================
  (
    'Apertura y presentación de la jornada',
    'Conferencia',
    '2026-05-05',
    '2026-05-05',
    'Martes',
    '14:00:00',
    '14:30:00',
    '30 minutos',
    'Pertenecer a la comunidad universitaria.',
    0.00,
    100,
    100,
    'Presentación de los objetivos y contenidos de la jornada de comunicación y oratoria.',
    23,
    'Activo'
  ),
  (
    'Técnicas de comunicación efectiva',
    'Taller',
    '2026-05-05',
    '2026-05-05',
    'Martes',
    '14:30:00',
    '15:30:00',
    '1 hora',
    'Participación en la jornada.',
    0.00,
    100,
    100,
    'Taller sobre técnicas para mejorar la claridad, seguridad y efectividad de la comunicación.',
    23,
    'Activo'
  ),
  (
    'Práctica de expresión oral',
    'Práctica',
    '2026-05-05',
    '2026-05-05',
    'Martes',
    '15:45:00',
    '16:45:00',
    '1 hora',
    'Participación en el taller.',
    0.00,
    100,
    100,
    'Ejercicios prácticos de exposición y expresión oral frente a los participantes.',
    23,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 24
  -- Taller de Manejo de la Voz y Lenguaje Corporal
  -- =====================================================
  (
    'Ejercicios de respiración y vocalización',
    'Taller práctico',
    '2026-05-09',
    '2026-05-09',
    'Sábado',
    '09:30:00',
    '10:15:00',
    '45 minutos',
    'Interés en mejorar la expresión oral.',
    0.00,
    40,
    40,
    'Ejercicios destinados a mejorar la respiración, vocalización y proyección de la voz.',
    24,
    'Activo'
  ),
  (
    'Técnicas de proyección de la voz',
    'Taller',
    '2026-05-09',
    '2026-05-09',
    'Sábado',
    '10:25:00',
    '11:15:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    40,
    40,
    'Prácticas para controlar volumen, ritmo, pausas y entonación durante una exposición.',
    24,
    'Activo'
  ),
  (
    'Postura y lenguaje corporal',
    'Taller práctico',
    '2026-05-09',
    '2026-05-09',
    'Sábado',
    '11:25:00',
    '12:15:00',
    '50 minutos',
    'Participación en las actividades anteriores.',
    0.00,
    40,
    40,
    'Ejercicios para mejorar postura, gestos, desplazamiento y contacto visual.',
    24,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 25
  -- Encuentro de Formación Litúrgica y Servicio
  -- =====================================================
  (
    'Introducción al servicio litúrgico',
    'Formación',
    '2026-05-14',
    '2026-05-14',
    'Jueves',
    '16:00:00',
    '16:45:00',
    '45 minutos',
    'Interés en participar en actividades litúrgicas.',
    0.00,
    50,
    50,
    'Presentación sobre el significado del servicio y la participación dentro de la liturgia.',
    25,
    'Activo'
  ),
  (
    'Organización de los servicios litúrgicos',
    'Planificación',
    '2026-05-14',
    '2026-05-14',
    'Jueves',
    '16:55:00',
    '17:40:00',
    '45 minutos',
    'Participación en el encuentro.',
    0.00,
    50,
    50,
    'Coordinación y distribución de responsabilidades entre los diferentes servidores litúrgicos.',
    25,
    'Activo'
  ),
  (
    'Práctica de participación litúrgica',
    'Práctica',
    '2026-05-14',
    '2026-05-14',
    'Jueves',
    '17:45:00',
    '18:45:00',
    '1 hora',
    'Participación en la formación.',
    0.00,
    50,
    50,
    'Práctica de las funciones asignadas para fortalecer la coordinación durante las celebraciones.',
    25,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 26
  -- Conferencia Universitaria sobre Liderazgo y Comunicación
  -- =====================================================
  (
    'Apertura de la conferencia',
    'Conferencia',
    '2026-05-19',
    '2026-05-19',
    'Martes',
    '18:00:00',
    '18:20:00',
    '20 minutos',
    'Participación abierta.',
    0.00,
    120,
    120,
    'Presentación de la conferencia y de los principales temas que serán abordados.',
    26,
    'Activo'
  ),
  (
    'Liderazgo y comunicación efectiva',
    'Conferencia',
    '2026-05-19',
    '2026-05-19',
    'Martes',
    '18:20:00',
    '19:20:00',
    '1 hora',
    'Participación abierta.',
    0.00,
    120,
    120,
    'Exposición sobre la relación entre liderazgo, comunicación y capacidad de trabajo en equipo.',
    26,
    'Activo'
  ),
  (
    'Conversatorio con los participantes',
    'Conversatorio',
    '2026-05-19',
    '2026-05-19',
    'Martes',
    '19:30:00',
    '20:15:00',
    '45 minutos',
    'Participación en la conferencia.',
    0.00,
    120,
    120,
    'Espacio de preguntas, intercambio de experiencias y reflexión sobre liderazgo.',
    26,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 27
  -- Encuentro de Lectores y Servidores Litúrgicos
  -- =====================================================
  (
    'Formación para lectores litúrgicos',
    'Formación',
    '2026-05-23',
    '2026-05-23',
    'Sábado',
    '10:00:00',
    '10:45:00',
    '45 minutos',
    'Interés en participar como lector litúrgico.',
    0.00,
    50,
    50,
    'Formación sobre la preparación y proclamación adecuada de las lecturas.',
    27,
    'Activo'
  ),
  (
    'Práctica de lectura y proclamación',
    'Práctica',
    '2026-05-23',
    '2026-05-23',
    'Sábado',
    '10:55:00',
    '11:45:00',
    '50 minutos',
    'Participación en la formación.',
    0.00,
    50,
    50,
    'Ejercicios prácticos de dicción, pausas, volumen y expresión durante la proclamación.',
    27,
    'Activo'
  ),
  (
    'Coordinación de servidores litúrgicos',
    'Coordinación',
    '2026-05-23',
    '2026-05-23',
    'Sábado',
    '11:55:00',
    '12:40:00',
    '45 minutos',
    'Participación en el encuentro.',
    0.00,
    50,
    50,
    'Coordinación de las funciones y responsabilidades de los servidores durante las celebraciones.',
    27,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 28
  -- Festival de Expresión Oral Universitaria
  -- =====================================================
  (
    'Registro y presentación de participantes',
    'Organización',
    '2026-05-29',
    '2026-05-29',
    'Viernes',
    '14:30:00',
    '15:00:00',
    '30 minutos',
    'Inscripción previa al festival.',
    0.00,
    100,
    100,
    'Registro de participantes y explicación de la dinámica del festival.',
    28,
    'Activo'
  ),
  (
    'Presentación de discursos y exposiciones',
    'Oratoria',
    '2026-05-29',
    '2026-05-29',
    'Viernes',
    '15:00:00',
    '16:30:00',
    '1 hora y 30 minutos',
    'Inscripción previa.',
    0.00,
    100,
    100,
    'Presentación de discursos y exposiciones preparadas por los estudiantes.',
    28,
    'Activo'
  ),
  (
    'Evaluación de presentaciones',
    'Evaluación',
    '2026-05-29',
    '2026-05-29',
    'Viernes',
    '16:45:00',
    '17:30:00',
    '45 minutos',
    'Ser participante o evaluador.',
    0.00,
    100,
    100,
    'Evaluación de las presentaciones considerando expresión, argumentación y desenvolvimiento.',
    28,
    'Activo'
  ),
  (
    'Reconocimiento y cierre del festival',
    'Clausura',
    '2026-05-29',
    '2026-05-29',
    'Viernes',
    '17:30:00',
    '18:00:00',
    '30 minutos',
    'Participación en el festival.',
    0.00,
    100,
    100,
    'Reconocimiento a los participantes y cierre del festival universitario.',
    28,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 29
  -- Jornada de Oratoria y Debate Universitario
  -- =====================================================
  (
    'Introducción al debate y argumentación',
    'Formación',
    '2026-06-04',
    '2026-06-04',
    'Jueves',
    '09:00:00',
    '09:45:00',
    '45 minutos',
    'Interés en participar en actividades de debate.',
    0.00,
    80,
    80,
    'Introducción a los fundamentos de la argumentación y el debate académico.',
    29,
    'Activo'
  ),
  (
    'Taller de construcción de argumentos',
    'Taller',
    '2026-06-04',
    '2026-06-04',
    'Jueves',
    '09:55:00',
    '10:50:00',
    '55 minutos',
    'Participación en la jornada.',
    0.00,
    80,
    80,
    'Ejercicios para construir argumentos claros, coherentes y fundamentados.',
    29,
    'Activo'
  ),
  (
    'Debate entre participantes',
    'Debate',
    '2026-06-04',
    '2026-06-04',
    'Jueves',
    '11:00:00',
    '12:00:00',
    '1 hora',
    'Participación en el taller previo.',
    0.00,
    80,
    80,
    'Actividad práctica de debate sobre temas de interés universitario.',
    29,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 30
  -- Taller de Preparación de Discursos y Presentaciones
  -- =====================================================
  (
    'Estructura del discurso',
    'Taller',
    '2026-06-10',
    '2026-06-10',
    'Miércoles',
    '15:00:00',
    '15:50:00',
    '50 minutos',
    'Interés en desarrollar habilidades de oratoria.',
    0.00,
    45,
    45,
    'Técnicas para organizar introducción, desarrollo y conclusión de una presentación.',
    30,
    'Activo'
  ),
  (
    'Organización y desarrollo de ideas',
    'Taller práctico',
    '2026-06-10',
    '2026-06-10',
    'Miércoles',
    '16:00:00',
    '16:50:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    45,
    45,
    'Ejercicios para ordenar ideas y construir contenidos claros para una exposición.',
    30,
    'Activo'
  ),
  (
    'Práctica de presentaciones',
    'Práctica',
    '2026-06-10',
    '2026-06-10',
    'Miércoles',
    '17:00:00',
    '18:00:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    45,
    45,
    'Presentaciones breves de los participantes con retroalimentación del facilitador.',
    30,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 31
  -- Encuentro de Formación para la Animación Litúrgica
  -- =====================================================
  (
    'Funciones del animador litúrgico',
    'Formación',
    '2026-06-14',
    '2026-06-14',
    'Domingo',
    '10:00:00',
    '10:45:00',
    '45 minutos',
    'Interés en participar en la animación litúrgica.',
    0.00,
    50,
    50,
    'Formación sobre las funciones y responsabilidades del animador litúrgico.',
    31,
    'Activo'
  ),
  (
    'Técnicas de animación y participación',
    'Taller',
    '2026-06-14',
    '2026-06-14',
    'Domingo',
    '10:55:00',
    '11:45:00',
    '50 minutos',
    'Participación en el encuentro.',
    0.00,
    50,
    50,
    'Técnicas para favorecer la participación activa y ordenada de la comunidad.',
    31,
    'Activo'
  ),
  (
    'Práctica de animación litúrgica',
    'Práctica',
    '2026-06-14',
    '2026-06-14',
    'Domingo',
    '11:55:00',
    '12:45:00',
    '50 minutos',
    'Participación en las actividades formativas.',
    0.00,
    50,
    50,
    'Simulación de diferentes momentos de animación durante una celebración.',
    31,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 32
  -- Jornada de Comunicación, Ética y Responsabilidad
  -- =====================================================
  (
    'Comunicación responsable en la comunidad',
    'Conferencia',
    '2026-06-18',
    '2026-06-18',
    'Jueves',
    '14:30:00',
    '15:15:00',
    '45 minutos',
    'Participación abierta.',
    0.00,
    80,
    80,
    'Reflexión sobre el impacto de la comunicación y la responsabilidad al transmitir información.',
    32,
    'Activo'
  ),
  (
    'Taller de comunicación asertiva',
    'Taller',
    '2026-06-18',
    '2026-06-18',
    'Jueves',
    '15:25:00',
    '16:20:00',
    '55 minutos',
    'Participación en la jornada.',
    0.00,
    80,
    80,
    'Ejercicios para desarrollar una comunicación clara, respetuosa y asertiva.',
    32,
    'Activo'
  ),
  (
    'Análisis de casos de comunicación',
    'Trabajo grupal',
    '2026-06-18',
    '2026-06-18',
    'Jueves',
    '16:30:00',
    '17:30:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    80,
    80,
    'Análisis grupal de situaciones relacionadas con responsabilidad y ética en la comunicación.',
    32,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 33
  -- Encuentro Universitario de Reflexión y Participación
  -- =====================================================
  (
    'Dinámica de integración comunitaria',
    'Integración',
    '2026-06-23',
    '2026-06-23',
    'Martes',
    '09:30:00',
    '10:15:00',
    '45 minutos',
    'Participación abierta a estudiantes.',
    0.00,
    100,
    100,
    'Dinámica destinada a fortalecer la integración y participación de los estudiantes.',
    33,
    'Activo'
  ),
  (
    'Mesa de diálogo universitario',
    'Conversatorio',
    '2026-06-23',
    '2026-06-23',
    'Martes',
    '10:25:00',
    '11:20:00',
    '55 minutos',
    'Participación en el encuentro.',
    0.00,
    100,
    100,
    'Espacio de diálogo sobre experiencias, necesidades y propuestas de la comunidad universitaria.',
    33,
    'Activo'
  ),
  (
    'Reflexión sobre participación y compromiso',
    'Reflexión',
    '2026-06-23',
    '2026-06-23',
    'Martes',
    '11:30:00',
    '12:15:00',
    '45 minutos',
    'Participación en las actividades anteriores.',
    0.00,
    100,
    100,
    'Reflexión sobre el compromiso y la participación activa dentro de la comunidad universitaria.',
    33,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 34
  -- Cierre Semestral de Actividades de Oratoria y Liturgia
  -- =====================================================
  (
    'Presentación de resultados del semestre',
    'Presentación',
    '2026-06-27',
    '2026-06-27',
    'Sábado',
    '15:00:00',
    '15:45:00',
    '45 minutos',
    'Participación en las actividades del semestre.',
    0.00,
    100,
    100,
    'Presentación de los principales resultados y actividades desarrolladas durante el semestre.',
    34,
    'Activo'
  ),
  (
    'Espacio de reflexión y evaluación',
    'Reflexión',
    '2026-06-27',
    '2026-06-27',
    'Sábado',
    '15:55:00',
    '16:45:00',
    '50 minutos',
    'Participación en el cierre semestral.',
    0.00,
    100,
    100,
    'Evaluación participativa de las experiencias y aprendizajes obtenidos durante el semestre.',
    34,
    'Activo'
  ),
  (
    'Reconocimiento a participantes',
    'Reconocimiento',
    '2026-06-27',
    '2026-06-27',
    'Sábado',
    '16:55:00',
    '17:30:00',
    '35 minutos',
    'Participación en las actividades del semestre.',
    0.00,
    100,
    100,
    'Reconocimiento a estudiantes y colaboradores que participaron activamente durante el semestre.',
    34,
    'Activo'
  ),
  (
    'Cierre y convivencia universitaria',
    'Convivencia',
    '2026-06-27',
    '2026-06-27',
    'Sábado',
    '17:30:00',
    '18:30:00',
    '1 hora',
    'Participación en el evento de cierre.',
    0.00,
    100,
    100,
    'Espacio de convivencia y cierre de las actividades del primer semestre.',
    34,
    'Activo'
  );
INSERT INTO actividades (
    nombre_actividad,
    tipo_actividad,
    fecha_inicio,
    fecha_fin,
    dias_semana,
    hora_inicio,
    hora_fin,
    duracion,
    requisitos,
    costo,
    cupo_maximo,
    cupo_disponible,
    descripcion,
    id_evento,
    estado
  )
VALUES -- =====================================================
  -- EVENTO 35
  -- Encuentro de Integración y Formación Universitaria
  -- =====================================================
  (
    'Registro y bienvenida de participantes',
    'Integración',
    '2026-07-04',
    '2026-07-04',
    'Sábado',
    '09:00:00',
    '09:30:00',
    '30 minutos',
    'Pertenecer a la comunidad universitaria.',
    0.00,
    100,
    100,
    'Registro y bienvenida de los participantes del encuentro universitario.',
    35,
    'Activo'
  ),
  (
    'Dinámica de integración universitaria',
    'Dinámica',
    '2026-07-04',
    '2026-07-04',
    'Sábado',
    '09:30:00',
    '10:30:00',
    '1 hora',
    'Participación en el encuentro.',
    0.00,
    100,
    100,
    'Dinámicas grupales destinadas a fortalecer la convivencia y la integración entre estudiantes.',
    35,
    'Activo'
  ),
  (
    'Taller sobre participación y compromiso',
    'Taller',
    '2026-07-04',
    '2026-07-04',
    'Sábado',
    '10:45:00',
    '11:45:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    100,
    100,
    'Espacio formativo sobre participación, compromiso y responsabilidad dentro de la comunidad universitaria.',
    35,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 36
  -- Taller Intensivo de Oratoria y Expresión Pública
  -- =====================================================
  (
    'Técnicas de respiración y vocalización',
    'Taller práctico',
    '2026-07-09',
    '2026-07-09',
    'Jueves',
    '14:30:00',
    '15:15:00',
    '45 minutos',
    'Interés en mejorar la expresión oral.',
    0.00,
    40,
    40,
    'Ejercicios prácticos de respiración, vocalización y preparación de la voz.',
    36,
    'Activo'
  ),
  (
    'Manejo de la voz ante el público',
    'Taller',
    '2026-07-09',
    '2026-07-09',
    'Jueves',
    '15:25:00',
    '16:15:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    40,
    40,
    'Técnicas para controlar volumen, ritmo, pausas y entonación durante una presentación.',
    36,
    'Activo'
  ),
  (
    'Práctica de expresión pública',
    'Práctica',
    '2026-07-09',
    '2026-07-09',
    'Jueves',
    '16:25:00',
    '17:30:00',
    '1 hora y 5 minutos',
    'Participación en las actividades anteriores.',
    0.00,
    40,
    40,
    'Práctica individual de discursos breves y presentaciones frente a los participantes.',
    36,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 37
  -- Jornada de Formación en Comunicación y Liderazgo
  -- =====================================================
  (
    'Fundamentos del liderazgo universitario',
    'Formación',
    '2026-07-15',
    '2026-07-15',
    'Miércoles',
    '09:30:00',
    '10:15:00',
    '45 minutos',
    'Participación abierta a estudiantes.',
    0.00,
    80,
    80,
    'Introducción a los principios del liderazgo y su importancia en la vida universitaria.',
    37,
    'Activo'
  ),
  (
    'Comunicación efectiva para líderes',
    'Taller',
    '2026-07-15',
    '2026-07-15',
    'Miércoles',
    '10:25:00',
    '11:20:00',
    '55 minutos',
    'Participación en la jornada.',
    0.00,
    80,
    80,
    'Técnicas de comunicación para coordinar equipos y transmitir ideas de manera efectiva.',
    37,
    'Activo'
  ),
  (
    'Dinámica de liderazgo y trabajo en equipo',
    'Dinámica',
    '2026-07-15',
    '2026-07-15',
    'Miércoles',
    '11:30:00',
    '12:30:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    80,
    80,
    'Actividad grupal para desarrollar liderazgo colaborativo y capacidad de trabajo en equipo.',
    37,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 38
  -- Encuentro de Preparación y Coordinación Litúrgica
  -- =====================================================
  (
    'Revisión de la celebración litúrgica',
    'Planificación',
    '2026-07-20',
    '2026-07-20',
    'Lunes',
    '16:00:00',
    '16:45:00',
    '45 minutos',
    'Participación en el equipo litúrgico.',
    0.00,
    50,
    50,
    'Revisión de los elementos y momentos principales de la celebración litúrgica.',
    38,
    'Activo'
  ),
  (
    'Distribución de responsabilidades',
    'Coordinación',
    '2026-07-20',
    '2026-07-20',
    'Lunes',
    '16:55:00',
    '17:40:00',
    '45 minutos',
    'Participación en el encuentro.',
    0.00,
    50,
    50,
    'Organización y distribución de las funciones de lectores, animadores y servidores.',
    38,
    'Activo'
  ),
  (
    'Ensayo general de la celebración',
    'Ensayo',
    '2026-07-20',
    '2026-07-20',
    'Lunes',
    '17:45:00',
    '18:45:00',
    '1 hora',
    'Participación en las actividades de preparación.',
    0.00,
    50,
    50,
    'Ensayo general de las intervenciones y responsabilidades asignadas.',
    38,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 39
  -- Jornada de Reflexión y Comunicación Comunitaria
  -- =====================================================
  (
    'Dinámica de escucha activa',
    'Dinámica',
    '2026-07-25',
    '2026-07-25',
    'Sábado',
    '10:00:00',
    '10:45:00',
    '45 minutos',
    'Participación abierta.',
    0.00,
    60,
    60,
    'Actividad para fortalecer la escucha, atención y comprensión entre los participantes.',
    39,
    'Activo'
  ),
  (
    'Taller de comunicación interpersonal',
    'Taller',
    '2026-07-25',
    '2026-07-25',
    'Sábado',
    '10:55:00',
    '11:45:00',
    '50 minutos',
    'Participación en la jornada.',
    0.00,
    60,
    60,
    'Taller sobre comunicación interpersonal, empatía y convivencia comunitaria.',
    39,
    'Activo'
  ),
  (
    'Conversatorio sobre convivencia universitaria',
    'Conversatorio',
    '2026-07-25',
    '2026-07-25',
    'Sábado',
    '11:55:00',
    '12:45:00',
    '50 minutos',
    'Participación en las actividades anteriores.',
    0.00,
    60,
    60,
    'Espacio de diálogo sobre comunicación, respeto y convivencia dentro de la universidad.',
    39,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 40
  -- Muestra Universitaria de Oratoria
  -- =====================================================
  (
    'Registro y preparación de participantes',
    'Organización',
    '2026-07-30',
    '2026-07-30',
    'Jueves',
    '15:00:00',
    '15:30:00',
    '30 minutos',
    'Inscripción previa a la muestra.',
    0.00,
    100,
    100,
    'Registro de participantes y preparación previa a las presentaciones.',
    40,
    'Activo'
  ),
  (
    'Presentación de discursos',
    'Oratoria',
    '2026-07-30',
    '2026-07-30',
    'Jueves',
    '15:30:00',
    '16:45:00',
    '1 hora y 15 minutos',
    'Inscripción previa.',
    0.00,
    100,
    100,
    'Presentación de discursos preparados por estudiantes sobre diferentes temas.',
    40,
    'Activo'
  ),
  (
    'Retroalimentación de las presentaciones',
    'Evaluación',
    '2026-07-30',
    '2026-07-30',
    'Jueves',
    '17:00:00',
    '17:45:00',
    '45 minutos',
    'Participación en la muestra.',
    0.00,
    100,
    100,
    'Retroalimentación sobre expresión, estructura, argumentación y desenvolvimiento.',
    40,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 41
  -- Jornada Universitaria de Integración y Participación
  -- =====================================================
  (
    'Bienvenida y dinámica de integración',
    'Integración',
    '2026-08-05',
    '2026-08-05',
    'Miércoles',
    '09:00:00',
    '09:45:00',
    '45 minutos',
    'Participación abierta.',
    0.00,
    100,
    100,
    'Actividad de bienvenida para promover la integración entre los participantes.',
    41,
    'Activo'
  ),
  (
    'Taller de participación estudiantil',
    'Taller',
    '2026-08-05',
    '2026-08-05',
    'Miércoles',
    '09:55:00',
    '10:50:00',
    '55 minutos',
    'Participación en la jornada.',
    0.00,
    100,
    100,
    'Taller sobre mecanismos y oportunidades de participación dentro de la comunidad universitaria.',
    41,
    'Activo'
  ),
  (
    'Actividad colaborativa universitaria',
    'Trabajo grupal',
    '2026-08-05',
    '2026-08-05',
    'Miércoles',
    '11:00:00',
    '12:00:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    100,
    100,
    'Actividad grupal orientada a fortalecer la colaboración y el sentido de comunidad.',
    41,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 42
  -- Taller de Comunicación Persuasiva y Argumentación
  -- =====================================================
  (
    'Fundamentos de la comunicación persuasiva',
    'Taller',
    '2026-08-10',
    '2026-08-10',
    'Lunes',
    '14:00:00',
    '14:50:00',
    '50 minutos',
    'Interés en desarrollar habilidades comunicativas.',
    0.00,
    45,
    45,
    'Introducción a los principios de la comunicación persuasiva y efectiva.',
    42,
    'Activo'
  ),
  (
    'Construcción de argumentos',
    'Taller práctico',
    '2026-08-10',
    '2026-08-10',
    'Lunes',
    '15:00:00',
    '15:50:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    45,
    45,
    'Ejercicios para desarrollar argumentos claros, coherentes y fundamentados.',
    42,
    'Activo'
  ),
  (
    'Práctica de debate y persuasión',
    'Práctica',
    '2026-08-10',
    '2026-08-10',
    'Lunes',
    '16:00:00',
    '17:00:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    45,
    45,
    'Ejercicio práctico de debate y exposición de argumentos ante otros participantes.',
    42,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 43
  -- Encuentro de Formación para Equipos Litúrgicos
  -- =====================================================
  (
    'Organización del equipo litúrgico',
    'Planificación',
    '2026-08-15',
    '2026-08-15',
    'Sábado',
    '10:00:00',
    '10:45:00',
    '45 minutos',
    'Interés en participar en equipos litúrgicos.',
    0.00,
    60,
    60,
    'Presentación de las funciones y organización de los equipos que participan en las celebraciones.',
    43,
    'Activo'
  ),
  (
    'Formación de lectores y animadores',
    'Formación',
    '2026-08-15',
    '2026-08-15',
    'Sábado',
    '10:55:00',
    '11:45:00',
    '50 minutos',
    'Participación en el encuentro.',
    0.00,
    60,
    60,
    'Formación específica para lectores, animadores y servidores litúrgicos.',
    43,
    'Activo'
  ),
  (
    'Práctica de coordinación litúrgica',
    'Práctica',
    '2026-08-15',
    '2026-08-15',
    'Sábado',
    '11:55:00',
    '12:45:00',
    '50 minutos',
    'Participación en la formación.',
    0.00,
    60,
    60,
    'Práctica de coordinación entre los diferentes miembros del equipo litúrgico.',
    43,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 44
  -- Conferencia Universitaria sobre Comunicación y Valores
  -- =====================================================
  (
    'Apertura y presentación de la conferencia',
    'Conferencia',
    '2026-08-19',
    '2026-08-19',
    'Miércoles',
    '18:00:00',
    '18:20:00',
    '20 minutos',
    'Participación abierta.',
    0.00,
    120,
    120,
    'Presentación de los objetivos y temas principales de la conferencia.',
    44,
    'Activo'
  ),
  (
    'Comunicación responsable y valores',
    'Conferencia',
    '2026-08-19',
    '2026-08-19',
    'Miércoles',
    '18:20:00',
    '19:20:00',
    '1 hora',
    'Participación abierta.',
    0.00,
    120,
    120,
    'Reflexión sobre comunicación responsable, respeto, empatía y valores.',
    44,
    'Activo'
  ),
  (
    'Conversatorio con la comunidad universitaria',
    'Conversatorio',
    '2026-08-19',
    '2026-08-19',
    'Miércoles',
    '19:30:00',
    '20:15:00',
    '45 minutos',
    'Participación en la conferencia.',
    0.00,
    120,
    120,
    'Espacio de preguntas, diálogo e intercambio de experiencias entre los participantes.',
    44,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 45
  -- Encuentro de Oratoria, Liderazgo y Participación Estudiantil
  -- =====================================================
  (
    'Taller de liderazgo y expresión oral',
    'Taller',
    '2026-08-24',
    '2026-08-24',
    'Lunes',
    '14:30:00',
    '15:20:00',
    '50 minutos',
    'Participación abierta a estudiantes.',
    0.00,
    70,
    70,
    'Taller para fortalecer las habilidades de liderazgo mediante la expresión oral.',
    45,
    'Activo'
  ),
  (
    'Dinámica de liderazgo participativo',
    'Dinámica',
    '2026-08-24',
    '2026-08-24',
    'Lunes',
    '15:30:00',
    '16:20:00',
    '50 minutos',
    'Participación en el taller.',
    0.00,
    70,
    70,
    'Dinámica grupal para desarrollar liderazgo, participación y trabajo colaborativo.',
    45,
    'Activo'
  ),
  (
    'Presentaciones de liderazgo estudiantil',
    'Oratoria',
    '2026-08-24',
    '2026-08-24',
    'Lunes',
    '16:30:00',
    '17:30:00',
    '1 hora',
    'Participación en las actividades anteriores.',
    0.00,
    70,
    70,
    'Presentaciones breves de propuestas e ideas desarrolladas por los estudiantes.',
    45,
    'Activo'
  ),
  -- =====================================================
  -- EVENTO 46
  -- Festival Universitario de Comunicación y Expresión
  -- =====================================================
  (
    'Registro y apertura del festival',
    'Organización',
    '2026-08-29',
    '2026-08-29',
    'Sábado',
    '09:00:00',
    '09:30:00',
    '30 minutos',
    'Inscripción previa al festival.',
    0.00,
    120,
    120,
    'Registro de participantes y presentación de las actividades programadas.',
    46,
    'Activo'
  ),
  (
    'Muestra de discursos y expresión oral',
    'Oratoria',
    '2026-08-29',
    '2026-08-29',
    'Sábado',
    '09:30:00',
    '10:45:00',
    '1 hora y 15 minutos',
    'Inscripción previa.',
    0.00,
    120,
    120,
    'Presentación de discursos y exposiciones preparadas por los estudiantes.',
    46,
    'Activo'
  ),
  (
    'Presentaciones artísticas y comunicativas',
    'Presentación',
    '2026-08-29',
    '2026-08-29',
    'Sábado',
    '11:00:00',
    '12:00:00',
    '1 hora',
    'Participación en el festival.',
    0.00,
    120,
    120,
    'Espacio de expresión y participación mediante presentaciones individuales y grupales.',
    46,
    'Activo'
  ),
  (
    'Cierre y reconocimiento de participantes',
    'Clausura',
    '2026-08-29',
    '2026-08-29',
    'Sábado',
    '12:00:00',
    '12:30:00',
    '30 minutos',
    'Participación en el festival.',
    0.00,
    120,
    120,
    'Cierre del festival y reconocimiento a los participantes.',
    46,
    'Activo'
  );
ALTER TABLE actividades DROP FOREIGN KEY actividades_ibfk_1;
ALTER TABLE actividades
ADD CONSTRAINT actividades_ibfk_1 FOREIGN KEY (id_evento) REFERENCES eventos(id_evento) ON UPDATE CASCADE ON DELETE CASCADE;