INSERT INTO universidades (
    id_universidad,
    nombre,
    sigla,
    ciudad,
    direccion,
    telefono,
    correo,
    sitio_web,
    estado
  )
VALUES (
    2,
    'Universidad Mayor de San Andrés',
    'UMSA',
    'La Paz',
    'Av. Villazón N° 1995',
    '+591 2 2441570',
    'info@umsa.bo',
    'https://www.umsa.bo/',
    'Activo'
  ),
  (
    3,
    'Universidad Católica Boliviana San Pablo',
    'UCB',
    'La Paz',
    'Av. 14 de Septiembre N° 4807',
    '+591 2 2782222',
    'info@ucb.edu.bo',
    'https://www.ucb.edu.bo/',
    'Activo'
  ),
  (
    4,
    'Universidad Privada Boliviana',
    'UPB',
    'La Paz',
    'Av. Hernando Siles N° 5080',
    '+591 2 2166566',
    'info@upb.edu',
    'https://www.upb.edu/',
    'Activo'
  ),
  (
    6,
    'Universidad Mayor de San Simón',
    'UMSS',
    'Cochabamba',
    'Av. Ballivián N° 591',
    '+591 4 4252981',
    'info@umss.edu.bo',
    'https://www.umss.edu.bo/',
    'Activo'
  ),
  (
    7,
    'Universidad Privada del Valle',
    'UNIVALLE',
    'Cochabamba',
    'Av. América N° 165',
    '+591 4 4318800',
    'info@univalle.edu',
    'https://www.univalle.edu/',
    'Activo'
  ),
  (
    9,
    'Universidad Autónoma Gabriel René Moreno',
    'UAGRM',
    'Santa Cruz',
    'Av. Busch, Ciudad Universitaria',
    '+591 3 3366000',
    'info@uagrm.edu.bo',
    'https://www.uagrm.edu.bo/',
    'Activo'
  ),
  (
    10,
    'Universidad Privada de Santa Cruz de la Sierra',
    'UPSA',
    'Santa Cruz',
    'Av. Paraguá, 4to Anillo',
    '+591 3 3464000',
    'info@upsa.edu.bo',
    'https://www.upsa.edu.bo/',
    'Activo'
  ),
  (
    11,
    'Universidad Tecnológica Privada de Santa Cruz',
    'UTEPSA',
    'Santa Cruz',
    'Av. Noel Kempff Mercado N° 715',
    '+591 3 3366666',
    'info@utepsa.edu',
    'https://www.utepsa.edu/',
    'Activo'
  ),
  (
    12,
    'Universidad San Francisco Xavier de Chuquisaca',
    'USFX',
    'Sucre',
    'Calle Dalence N° 115',
    '+591 4 6451221',
    'info@usfx.bo',
    'https://www.usfx.bo/',
    'Activo'
  ),
  (
    13,
    'Universidad Privada del Valle',
    'UNIVALLE',
    'Sucre',
    'Av. Gregorio Donoso N° 60',
    '+591 4 6454400',
    'sucre@univalle.edu',
    'https://www.univalle.edu/',
    'Activo'
  ),
  (
    14,
    'Universidad Autónoma Juan Misael Saracho',
    'UAJMS',
    'Tarija',
    'Av. Víctor Paz Estenssoro N° 149',
    '+591 4 6643112',
    'info@uajms.edu.bo',
    'https://www.uajms.edu.bo/',
    'Activo'
  ),
  (
    15,
    'Universidad Técnica de Oruro',
    'UTO',
    'Oruro',
    'Av. 6 de Octubre N° 5715',
    '+591 2 5270331',
    'info@uto.edu.bo',
    'https://www.uto.edu.bo/',
    'Activo'
  ),
  (
    16,
    'Universidad Autónoma Tomás Frías',
    'UATF',
    'Potosí',
    'Av. El Maestro S/N',
    '+591 2 6243100',
    'info@uatf.edu.bo',
    'https://www.uatf.edu.bo/',
    'Activo'
  ),
  (
    17,
    'Universidad Amazónica de Pando',
    'UAP',
    'Cobija',
    'Av. Las Palmas S/N',
    '+591 3 8422417',
    'info@uap.edu.bo',
    'https://www.uap.edu.bo/',
    'Activo'
  ),
  (
    18,
    'Universidad Pública de El Alto',
    'UPEA',
    'El Alto',
    'Av. Sucre A S/N, Villa Esperanza',
    '+591 2 2845800',
    'info@upea.bo',
    'https://www.upea.bo/',
    'Activo'
  ),
  (
    19,
    'Universidad Evangélica Boliviana',
    'UEB',
    'Santa Cruz',
    'Av. Moscú N° 700',
    '+591 3 3523333',
    'info@ueb.edu.bo',
    'https://www.ueb.edu.bo/',
    'Activo'
  ),
  (
    20,
    'Universidad NUR',
    'NUR',
    'Santa Cruz',
    'Av. Cristo Redentor Km 13',
    '+591 3 3363939',
    'info@nur.edu',
    'https://www.nur.edu/',
    'Activo'
  );
INSERT INTO personas (
    ci,
    nombres,
    apellidos,
    genero,
    direccion,
    telefono,
    correo,
    password,
    tipo_persona,
    id_universidad,
    id_usuario,
    estado,
    foto_perfil,
    token,
    token_expira
  )
VALUES (
    '10235567',
    'Carlos Andrés',
    'Mamani Quispe',
    'Masculino',
    'Zona Villa Copacabana',
    '71234567',
    'carlos.mamani@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Administrativo',
    1,
    1,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '104567893',
    'María Fernanda',
    'Condori Flores',
    'Femenino',
    'Zona Miraflores',
    '72345678',
    'maria.condori@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '109876542',
    'Diego Alejandro',
    'Choque Vargas',
    'Masculino',
    'Zona Villa Fátima',
    '73456789',
    'diego.choque@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '108765432',
    'Valeria Isabel',
    'Paredes Rojas',
    'Femenino',
    'Zona Sopocachi',
    '74567890',
    'valeria.paredes@umsa.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    2,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '103456781',
    'Juan Pablo',
    'Calle Apaza',
    'Masculino',
    'Zona San Pedro',
    '75678901',
    'juan.calle@emi.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    5,
    15,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '106543211',
    'Andrea Paola',
    'López Huanca',
    'Femenino',
    'Zona Tembladerani',
    '76789012',
    'andrea.lopez@umss.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    6,
    14,
    'Inactivo',
    NULL,
    NULL,
    NULL
  ),
  (
    '101234566',
    'Miguel Ángel',
    'Ticona Mamani',
    'Masculino',
    'Zona Periférica',
    '77890123',
    'miguel.ticona@upb.edu',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Docente',
    4,
    16,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '107890125',
    'Daniela Sofía',
    'Fernández Cruz',
    'Femenino',
    'Zona Achumani',
    '78901234',
    'daniela.fernandez@ucb.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    3,
    17,
    'Inactivo',
    NULL,
    NULL,
    NULL
  ),
  (
    '105678902',
    'Luis Fernando',
    'Quisbert Callisaya',
    'Masculino',
    'Zona El Alto',
    '79012345',
    'luis.quisbert@upea.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    18,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '110234563',
    'Gabriela Alejandra',
    'Ramos Mendoza',
    'Femenino',
    'Zona Calacoto',
    '70123456',
    'gabriela.ramos@uagrm.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    9,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '111345674',
    'Rodrigo Sebastián',
    'Vargas Torrez',
    'Masculino',
    'Zona Obrajes',
    '71239845',
    'rodrigo.vargas@upsa.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    10,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '112456787',
    'Camila Nicole',
    'Gutiérrez Silva',
    'Femenino',
    'Zona Calacoto',
    '72348956',
    'camila.gutierrez@usfx.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    12,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '113567896',
    'Jorge Luis',
    'Huayta Condori',
    'Masculino',
    'Zona Villa Adela',
    '73457890',
    'jorge.huayta@uajms.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    14,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '114678905',
    'Natalia Beatriz',
    'Salazar Arias',
    'Femenino',
    'Zona Cota Cota',
    '74568901',
    'natalia.salazar@uto.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    15,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '115789012',
    'Fernando José',
    'Mendoza Nina',
    'Masculino',
    'Zona Villa Armonía',
    '75679012',
    'fernando.mendoza@uatf.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    16,
    17,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '116890121',
    'Paola Andrea',
    'Rojas Quispe',
    'Femenino',
    'Zona Miraflores',
    '76780123',
    'paola.rojas@uap.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    17,
    15,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '117901232',
    'Mauricio Daniel',
    'Apaza Flores',
    'Masculino',
    'Zona Villa San Antonio',
    '77891234',
    'mauricio.apaza@nur.edu',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    20,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '118012342',
    'Lucía Gabriela',
    'Mamani Vargas',
    'Femenino',
    'Zona Sopocachi',
    '78902345',
    'lucia.mamani@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '119123459',
    'Óscar Eduardo',
    'Condori Quispe',
    'Masculino',
    'Zona Alto Obrajes',
    '79013456',
    'oscar.condori@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '120234561',
    'Ana María',
    'Cruz Mamani',
    'Femenino',
    'Zona Villa Fátima',
    '70124567',
    'ana.cruz@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  );
INSERT INTO personas (
    ci,
    nombres,
    apellidos,
    genero,
    direccion,
    telefono,
    correo,
    password,
    tipo_persona,
    id_universidad,
    id_usuario,
    estado,
    foto_perfil,
    token,
    token_expira
  )
VALUES (
    '12134567',
    'Alejandro',
    'Fernández Mamani',
    'Masculino',
    'Zona Miraflores',
    '71123456',
    'alejandro.fernandez@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12245678',
    'Sofía',
    'Quispe Vargas',
    'Femenino',
    'Zona Sopocachi',
    '72234567',
    'sofia.quispe@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12356789',
    'Mateo',
    'Rojas Condori',
    'Masculino',
    'Zona Villa Fátima',
    '73345678',
    'mateo.rojas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12467890',
    'Carla',
    'Mendoza Flores',
    'Femenino',
    'Zona Obrajes',
    '74456789',
    'carla.mendoza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12578901',
    'Sebastián',
    'Torrez Apaza',
    'Masculino',
    'Zona San Pedro',
    '75567890',
    'sebastian.torrez@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12689012',
    'Mariana',
    'Vargas Callisaya',
    'Femenino',
    'Zona Achumani',
    '76678901',
    'mariana.vargas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    1,
    15,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12790123',
    'Gabriel',
    'Huanca Nina',
    'Masculino',
    'Zona Tembladerani',
    '77789012',
    'gabriel.huanca@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    1,
    14,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12801234',
    'Daniel',
    'Paredes Quispe',
    'Masculino',
    'Zona Calacoto',
    '78890123',
    'daniel.paredes@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Docente',
    1,
    16,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '12912345',
    'Laura',
    'Mamani Rojas',
    'Femenino',
    'Zona Alto Obrajes',
    '79901234',
    'laura.mamani@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13023456',
    'Bruno',
    'Cruz Choque',
    'Masculino',
    'Zona Villa Copacabana',
    '70012345',
    'bruno.cruz@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13134567',
    'Valentina',
    'Arias Condori',
    'Femenino',
    'Zona Miraflores',
    '71123489',
    'valentina.arias@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13245678',
    'Nicolás',
    'Salazar Quispe',
    'Masculino',
    'Zona Villa San Antonio',
    '72234589',
    'nicolas.salazar@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13356789',
    'Isabela',
    'Flores Mamani',
    'Femenino',
    'Zona Cota Cota',
    '73345689',
    'isabela.flores@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13467890',
    'Renato',
    'Vargas Choque',
    'Masculino',
    'Zona Periférica',
    '74456789',
    'renato.vargas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13578901',
    'Camila',
    'Apaza Rojas',
    'Femenino',
    'Zona Sopocachi',
    '75567891',
    'camila.apaza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13689012',
    'Esteban',
    'Mendoza Huanca',
    'Masculino',
    'Zona Achumani',
    '76678912',
    'esteban.mendoza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    12,
    'Suspendido',
    NULL,
    NULL,
    NULL
  ),
  (
    '13790123',
    'Patricia',
    'Calle Vargas',
    'Femenino',
    'Zona Calacoto',
    '77789023',
    'patricia.calle@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    17,
    'Inactivo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13801234',
    'Adrián',
    'Ticona Flores',
    'Masculino',
    'Zona El Alto',
    '78890134',
    'adrian.ticona@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '13912345',
    'Alejandra',
    'Gutiérrez Mamani',
    'Femenino',
    'Zona San Pedro',
    '79901245',
    'alejandra.gutierrez@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '14023456',
    'Ricardo',
    'Quisbert Condori',
    'Masculino',
    'Zona Villa Fátima',
    '70012356',
    'ricardo.quisbert@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  );
INSERT INTO personas (
    ci,
    nombres,
    apellidos,
    genero,
    direccion,
    telefono,
    correo,
    password,
    tipo_persona,
    id_universidad,
    id_usuario,
    estado,
    foto_perfil,
    token,
    token_expira
  )
VALUES (
    '16134567',
    'Adriana',
    'Mamani Quispe',
    'Femenino',
    'Zona Miraflores',
    '71134578',
    'adriana.mamani@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16245678',
    'Kevin',
    'Choque Vargas',
    'Masculino',
    'Zona Sopocachi',
    '72245679',
    'kevin.choque@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16356789',
    'Daniela',
    'Rojas Mamani',
    'Femenino',
    'Zona Villa Fátima',
    '73356780',
    'daniela.rojas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16467890',
    'Mauricio',
    'Condori Flores',
    'Masculino',
    'Zona Obrajes',
    '74467891',
    'mauricio.condori@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16578901',
    'Natalia',
    'Paredes Quispe',
    'Femenino',
    'Zona Achumani',
    '75578902',
    'natalia.paredes@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16689012',
    'Rodrigo',
    'Vargas Apaza',
    'Masculino',
    'Zona Calacoto',
    '76689013',
    'rodrigo.vargas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16790123',
    'Luciana',
    'Flores Mamani',
    'Femenino',
    'Zona Cota Cota',
    '77790124',
    'luciana.flores@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16801234',
    'Alejandro',
    'Quisbert Choque',
    'Masculino',
    'Zona Tembladerani',
    '78801235',
    'alejandro.quisbert@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '16912345',
    'Paola',
    'Mendoza Rojas',
    'Femenino',
    'Zona San Pedro',
    '79912346',
    'paola.mendoza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17023456',
    'Carlos',
    'Huanca Condori',
    'Masculino',
    'Zona Villa Copacabana',
    '70023457',
    'carlos.huanca@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17134567',
    'María José',
    'Ticona Vargas',
    'Femenino',
    'Zona Alto Obrajes',
    '71134579',
    'maria.ticona@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17245678',
    'Esteban',
    'Apaza Mamani',
    'Masculino',
    'Zona Villa San Antonio',
    '72245680',
    'esteban.apaza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17356789',
    'Claudia',
    'Salazar Quispe',
    'Femenino',
    'Zona Periférica',
    '73356781',
    'claudia.salazar@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17467890',
    'Javier',
    'Ramos Flores',
    'Masculino',
    'Zona El Alto',
    '74467892',
    'javier.ramos@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17578901',
    'Gabriela',
    'Mendoza Mamani',
    'Femenino',
    'Zona Miraflores',
    '75578903',
    'gabriela.mendoza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17689012',
    'Franco',
    'Calle Condori',
    'Masculino',
    'Zona Sopocachi',
    '76689014',
    'franco.calle@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    1,
    15,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17790123',
    'Jimena',
    'Vargas Rojas',
    'Femenino',
    'Zona Obrajes',
    '77790125',
    'jimena.vargas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    1,
    14,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17801234',
    'Sergio',
    'Quispe Huanca',
    'Masculino',
    'Zona Calacoto',
    '78801236',
    'sergio.quispe@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Docente',
    1,
    16,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '17912345',
    'Andrea',
    'Choque Mamani',
    'Femenino',
    'Zona Villa Fátima',
    '79912347',
    'andrea.choque@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    12,
    'Suspendido',
    NULL,
    NULL,
    NULL
  ),
  (
    '18023456',
    'Ricardo',
    'Poma Vargas',
    'Masculino',
    'Zona San Pedro',
    '70023468',
    'ricardo.poma@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    17,
    'Inactivo',
    NULL,
    NULL,
    NULL
  );
INSERT INTO personas (
    ci,
    nombres,
    apellidos,
    genero,
    direccion,
    telefono,
    correo,
    password,
    tipo_persona,
    id_universidad,
    id_usuario,
    estado,
    foto_perfil,
    token,
    token_expira
  )
VALUES (
    '18134567',
    'Marcelo',
    'Mamani Flores',
    'Masculino',
    'Zona Miraflores',
    '71145678',
    'marcelo.mamani@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18245678',
    'Valeria',
    'Choque Mamani',
    'Femenino',
    'Zona Sopocachi',
    '72256789',
    'valeria.choque@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18356789',
    'Andrés',
    'Vargas Quispe',
    'Masculino',
    'Zona Villa Fátima',
    '73367890',
    'andres.vargas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18467890',
    'María Elena',
    'Rojas Condori',
    'Femenino',
    'Zona Obrajes',
    '74478901',
    'maria.rojas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18578901',
    'Gabriel',
    'Apaza Vargas',
    'Masculino',
    'Zona Achumani',
    '75589012',
    'gabriel.apaza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18689012',
    'Carolina',
    'Quispe Mamani',
    'Femenino',
    'Zona Calacoto',
    '76690123',
    'carolina.quispe@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18790123',
    'Eduardo',
    'Huanca Rojas',
    'Masculino',
    'Zona Cota Cota',
    '77701234',
    'eduardo.huanca@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18801234',
    'Natalia',
    'Flores Quispe',
    'Femenino',
    'Zona Tembladerani',
    '78812345',
    'natalia.flores1@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '18912345',
    'Luis Alberto',
    'Mendoza Choque',
    'Masculino',
    'Zona San Pedro',
    '79923456',
    'luis.mendoza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19023456',
    'Patricia',
    'Condori Apaza',
    'Femenino',
    'Zona Villa Copacabana',
    '70034567',
    'patricia.condori@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    20,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19134567',
    'Rodrigo',
    'Ticona Flores',
    'Masculino',
    'Zona Alto Obrajes',
    '71145689',
    'rodrigo.ticona@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    5,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19245678',
    'Claudia',
    'Vargas Mamani',
    'Femenino',
    'Zona Villa San Antonio',
    '72256790',
    'claudia.vargas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19356789',
    'Fernando',
    'Quispe Choque',
    'Masculino',
    'Zona Periférica',
    '73367891',
    'fernando.quispe@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    18,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19467890',
    'Andrea',
    'Mamani Condori',
    'Femenino',
    'Zona El Alto',
    '74478912',
    'andrea.mamani@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    19,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19578901',
    'Jorge',
    'Rojas Huanca',
    'Masculino',
    'Zona Miraflores',
    '75589023',
    'jorge.rojas@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Voluntario',
    1,
    15,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19689012',
    'Mónica',
    'Apaza Vargas',
    'Femenino',
    'Zona Sopocachi',
    '76690134',
    'monica.apaza@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7NgOdjQh8uDld9A/G',
    'Voluntario',
    1,
    14,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19790123',
    'Esteban',
    'Mendoza Quispe',
    'Masculino',
    'Zona Calacoto',
    '77701245',
    'esteban.mendoza1@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Docente',
    1,
    16,
    'Activo',
    NULL,
    NULL,
    NULL
  ),
  (
    '19801234',
    'Alejandra',
    'Cruz Mamani',
    'Femenino',
    'Zona Villa Fátima',
    '78812356',
    'alejandra.cruz@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    12,
    'Suspendido',
    NULL,
    NULL,
    NULL
  ),
  (
    '19912345',
    'Marco Antonio',
    'Salazar Condori',
    'Masculino',
    'Zona Obrajes',
    '79923467',
    'marco.salazar@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    17,
    'Inactivo',
    NULL,
    NULL,
    NULL
  ),
  (
    '20023456',
    'Karen Daniela',
    'Huanca Rojas',
    'Femenino',
    'Zona Achumani',
    '70034578',
    'karen.huanca@usalesiana.edu.bo',
    '$2y$12$6TJRImhpszkeltP7Ng5ML.2sWr9a5X8ioss2uNgOdjQh8uDld9A/G',
    'Estudiante',
    1,
    4,
    'Activo',
    NULL,
    NULL,
    NULL
  );